# Generated by Django 5.1.2 on 2025-09-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('title', models.CharField(max_length=300, verbose_name='タイトル')),
                ('notice_type', models.SmallIntegerField(choices=[(1, '重要'), (2, '一般'), (3, 'イベント'), (4, 'メンテナンス')], verbose_name='お知らせ区分')),
                ('publish_start_at', models.DateTimeField(blank=True, null=True, verbose_name='公開開始日時')),
                ('publish_end_at', models.DateTimeField(blank=True, null=True, verbose_name='公開終了日時')),
                ('status', models.SmallIntegerField(choices=[(1, '下書き'), (2, '公開中'), (3, '非公開'), (4, '削除')], default=1, verbose_name='ステータス')),
                ('push_notification_scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='プッシュ通知予定日時')),
                ('push_notification_icon_url', models.URLField(blank=True, max_length=2048, verbose_name='プッシュ通知アイコンURL')),
                ('list_image_url', models.URLField(blank=True, max_length=2048, verbose_name='一覧画像URL')),
                ('detail_image_url', models.URLField(blank=True, max_length=2048, verbose_name='詳細画像URL')),
                ('short_description', models.CharField(blank=True, max_length=1000, verbose_name='簡易版本文')),
                ('description', models.TextField(blank=True, verbose_name='本文')),
                ('redirect_url', models.URLField(blank=True, max_length=2048, verbose_name='遷移先URL')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'db_table': 'notices',
                'ordering': ['-created_at'],
            },
        ),
    ]
