# Generated by Django 5.1.2 on 2025-09-10 12:42

import notices.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='push_notification_icon_url',
        ),
        migrations.AddField(
            model_name='notice',
            name='push_notification_icon',
            field=models.ImageField(blank=True, help_text='推奨サイズ: 512x512px', null=True, storage=notices.storages.PushNotificationIconStorage(), upload_to='push_notification_icons/', verbose_name='プッシュ通知アイコン'),
        ),
    ]
