# Generated by Django 5.1.2 on 2025-09-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_remove_notice_push_notification_icon_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='push_notification_icon',
        ),
        migrations.AddField(
            model_name='notice',
            name='push_notification_icon_url',
            field=models.URLField(blank=True, help_text='推奨サイズ: 512x512px。アップロードはサービスクラス経由で行います。', max_length=2048, null=True, verbose_name='プッシュ通知アイコンURL'),
        ),
    ]
